#!/usr/bin/env bash
# Xpods management console lifecycle.
#
#   ./console.sh init      create .env with a random secret + admin password (once)
#   ./console.sh up        build and start the console (runs init if needed)
#   ./console.sh down      stop the console
#   ./console.sh logs      follow console logs
#   ./console.sh passwd    set a new admin password
#   ./console.sh status    container status
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(dirname "$DIR")"
ENV_FILE="$DIR/.env"
IMAGE="xpods-console:local"

die()  { echo "error: $*" >&2; exit 1; }
info() { echo "==> $*"; }

if docker info >/dev/null 2>&1; then
  :
elif sg docker -c "docker info" >/dev/null 2>&1; then
  docker() { sg docker -c "docker $(printf '%q ' "$@")"; }
else
  die "cannot talk to the Docker daemon (is it running, and are you in the docker group?)"
fi

compose() { docker compose --project-directory "$DIR" -f "$DIR/compose.yml" "$@"; }

random() { head -c 48 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c "$1"; }

hash_password() {
  docker image inspect "$IMAGE" >/dev/null 2>&1 || compose build console >&2
  docker run --rm --network none --entrypoint python "$IMAGE" \
    -c 'import sys; from app.auth import hash_password; print(hash_password(sys.argv[1]))' "$1"
}

set_env() {
  local key=$1 value=$2
  if grep -q "^$key=" "$ENV_FILE"; then
    sed -i "s|^$key=.*|$key=$value|" "$ENV_FILE"
  else
    echo "$key=$value" >> "$ENV_FILE"
  fi
}

cmd_init() {
  if [[ -f "$ENV_FILE" ]]; then
    info "$ENV_FILE already exists; refreshing host ids and paths"
  else
    info "creating $ENV_FILE"
    cat > "$ENV_FILE" <<EOF
# Xpods console settings (generated by console.sh). Keep this file private.
CONSOLE_HOST=127.0.0.1
CONSOLE_PORT=8088
CONSOLE_ADMIN_USER=admin
CONSOLE_ADMIN_PASSWORD_HASH=
CONSOLE_SECRET_KEY=$(random 48)
# Set true when served over HTTPS (reverse proxy); marks the session cookie Secure.
CONSOLE_COOKIE_SECURE=false
CONSOLE_SESSION_HOURS=12
# Delete ingested events older than N days (0 = keep forever). Raw logs are unaffected.
CONSOLE_RETENTION_DAYS=0
EOF
    chmod 600 "$ENV_FILE"
  fi
  set_env CONSOLE_UID "$(id -u)"
  set_env CONSOLE_GID "$(id -g)"
  set_env DOCKER_GID "$(stat -c %g /var/run/docker.sock)"
  set_env REPO_DIR "$REPO_DIR"
  mkdir -p "$DIR/data"

  if ! grep -q '^CONSOLE_ADMIN_PASSWORD_HASH=scrypt:' "$ENV_FILE"; then
    local pw; pw="$(random 20)"
    set_env CONSOLE_ADMIN_PASSWORD_HASH "$(hash_password "$pw")"
    echo
    echo "    Admin user:     $(sed -n 's/^CONSOLE_ADMIN_USER=//p' "$ENV_FILE")"
    echo "    Admin password: $pw"
    echo "    (shown once; change it with ./console.sh passwd)"
    echo
  fi
}

cmd_passwd() {
  [[ -f "$ENV_FILE" ]] || die "run ./console.sh init first"
  local pw pw2
  read -rsp "New admin password: " pw; echo
  read -rsp "Repeat: " pw2; echo
  [[ "$pw" == "$pw2" ]] || die "passwords do not match"
  (( ${#pw} >= 12 )) || die "use at least 12 characters"
  set_env CONSOLE_ADMIN_PASSWORD_HASH "$(hash_password "$pw")"
  info "password updated"
  if [[ -n "$(compose ps -q console 2>/dev/null)" ]]; then compose up -d console; fi
}

cmd_up() {
  cmd_init
  info "building and starting the console"
  compose up -d --build
  local host port
  host="$(sed -n 's/^CONSOLE_HOST=//p' "$ENV_FILE")"
  port="$(sed -n 's/^CONSOLE_PORT=//p' "$ENV_FILE")"
  info "console: http://$host:$port"
  [[ "$host" == "127.0.0.1" ]] && echo "    remote access: ssh -L $port:127.0.0.1:$port <this-host>"
}

case "${1:-}" in
  init)   cmd_init ;;
  up)     cmd_up ;;
  down)   compose down ;;
  logs)   compose logs -f --tail 200 ;;
  passwd) cmd_passwd ;;
  status) compose ps ;;
  *) sed -n '2,9p' "$0" | sed 's/^# \{0,1\}//'; exit 1 ;;
esac
